name: Build Vue-v
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'bgok'
          reponame: 'AntiochDAO.github.io'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          useyarn: true